### ISSUE TITLE
リスナーの声を追加

### ISSUE THREAD

**Issue by tomoya** [vim-jp-radio/LP#176]
Xのポストを埋め込んで、「リスナーの声」のセクションを追加する。
位置は番組へのおたよりの下

**Comment by ryoppippi** [comment]
twitterはこれで埋め込み
https://www.npmjs.com/package/sveltekit-tweet

試してうまくいっている例
https://github.com/vim-jp-radio/LP/commit/c30f5f6f1a610ee72138afefdcc4a3809ff1e411
https://38cc4931.lp-d1f.pages.dev
